### ISSUE TITLE
envkey-fetch_X.X.X_linux_arm64 missing from `ext/`

### ISSUE THREAD

**Issue by drcongo** [envkey/envkey-python#8]
Hello.

Now that I finally have an Apple silicon Mac, I've been experimenting with trying to get various projects running on it. For projects where we build an arm64 Ubuntu Docker container, and install the EnvKey Python package, running the project / tests fails with this stacktrace:

```
Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    import envkey  # NOQA
  File "/usr/local/lib/python3.8/dist-packages/envkey/__init__.py", line 7, in <module>
    load(is_init=True)
  File "/usr/local/lib/python3.8/dist-packages/envkey/loader.py", line 26, in load
    fetch_res = fetch_env(key, cache_enabled=cache_enabled)
  File "/usr/local/lib/python3.8/dist-packages/envkey/fetch.py", line 55, in fetch_env
    res = subprocess.check_output(args).decode(encoding="utf-8").rstrip()
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/envkey/ext/envkey-fetch_1.2.9_linux_arm64/envkey-fetch'
```

I've experimented a little, and found that I can install and run `envkey-fetch` manually inside the container (presumably this installs the linux_arm64 version), but the python package doesn't use the one on the path. Obviously the easiest fix here is to include the linux_arm64 `envkey-fetch` inside `ext/` - if that's a bad idea for reasons that I'm unaware of, I'd be happy to open a PR that tries to fall back to an `envkey-fetch` executable on the path.

**Comment by danenania** [comment]
Fixed in 1.3.2 -- sorry about the delay on this!
